const songs = [{ name: "Achy Breaky Heart", cover: "/images/billy.jpg", Artist: "Billy Ray Cyrus", Album: "Some Gave All", Release: 1992, Genre: "Country", source: "/music/achy.mp3", trackId: 1 },
{ name: "Baby", cover: "/images/world.jpg", Artist: "Justin Bieber", Album: "My World 2.0", Release: 2010, Genre: "Pop", source: "/music/baby.mp3", trackId: 2 },
{ name: "Barbie Girl", cover: "/images/aqua.jpg", Artist: "Aqua", Album: "Aquarium", Release: 1997, Genre: "Pop", source: "/music/barbie.mp3", trackId: 3 },
{ name: "Bye, Bye, Bye", cover: "/images/nsync.jpg", Artist: "*NSYNC", Album: "No Strings Attached", Release: 2000, Genre: "Pop", source: "/music/bye.mp3", trackId: 4 },
{ name: "Who Let The Dogs Out?", cover: "/images/baha.jpg", Artist: "Baha Men", Album: "Who Let The Dogs Out?", Release: 2000, Genre: "Pop", source: "/music/dogs.mp3", trackId: 5 },
{ name: "What Did The Fox Say?", cover: "/images/berlin.jpg", Artist: "Ylvis", Album: "Berlin Tag & Nacht 5", Release: 2014, Genre: "Dance/electronic, pop", source: "/music/fox.mp3", trackId: 6 },
{ name: "Let It Go", cover: "/images/froz.jpg", Artist: "Idina Menzel", Album: "Frozen", Release: 2013, Genre: "Pop", source: "/music/frozen.mp3", trackId: 7 },
{ name: "Gangnam Style", cover: "/images/PSY.jpg", Artist: "PSY", Album: "Psy 6(six Rules) Part 1", Release: 2012, Genre: "Dance-pop", source: "/music/gangnam.mp3", trackId: 8 },
{ name: "My Humps", cover: "/images/monkey.jpg", Artist: "The Black Eyed Peas", Album: "Monkey Business", Release: 2005, Genre: "Pop, Hip-hop/rap", source: "/music/humps.mp3", trackId: 9 },
{ name: "Ice, Ice Baby", cover: "/images/extreme.jpg", Artist: "Vanilla Ice", Album: "To The Extreme", Release: 1990, Genre: "Hip-hop/rap", source: "/music/ice.mp3", trackId: 10 },
{ name: "Livin La Vida Loca", cover: "/images/ricky.jpg", artist: "ricky Martin", Album: "Ricky Martin", Release: 1999, Genre: "Pop", source: "/music/loca.mp3", trackId: 11 },
{ name: "Macarena", cover: "/images/rio.jpg", Artist: "Los Del Rio", Album: "A Mi Me Gusta", Release: 1993, Genre: "Pop", source: "/music/macarena.mp3", trackId: 12 },
{ name: "Call Me Maybe", cover: "/images/kiss.jpg", Artist: "Carly Rae Jepsen", Album: "Kiss", Release: 2012, Genre: "Teen pop", source: "/music/maybe.mp3", trackId: 13 },
{ name: "Oops!..I Did It Again", cover: "/images/britney.jpg", Artist: "Britney Spears", Album: "Oops!...I Did It Again", Release: 2000, Genre: "Pop", source: "/music/oops.mp3", trackId: 14 },
{ name: "I'm Too Sexy", cover: "/images/up.jpg", Artist: "Right Said Fred", Album: "UP", Release: 1992, Genre: "Dance-pop", source: "/music/sexy.mp3", trackId: 15 },
{ name: "Shake It Off", cover: "/images/1989.jpg", Artist: "Taylor Swift", Album: "1989", Release: 2014, Genre: "Pop", source: "/music/shake-it.mp3", trackId: 16 },
{ name: "Thong Song", cover: "/images/sis1.jpg", Artist: "Sisqo", Album: "Unleash The Dragon", Release: 1999, Genre: "Contemporary R & B", source: "/music/thong.mp3", trackId: 17 },
{ name: "U Can't Touch This", cover: "/images/hammer.jpg", Artist: "M C Hammer", Album: "Please Hammer, Don't Hurt'Em", Release: 1990, Genre: "Pop", source: "/music/touch-this.mp3", trackId: 18 },
{ name: "Umbrella", cover: "/images/rihanna.jpg", Artist: "Rihanna", Album: "Good Girl Gone Bad", Release: 2007, Genre: "R & B/soul", source: "/music/Umbrella.mp3", trackId: 19 },
{ name: "Wannabe", cover: "/images/spice.jpg", Artist: "Spice Girls", Album: "Spice", Release: 1996, Genre: "Pop", source: "/music/wannabe.mp3", trackId: 20 }
]
module.exports = songs 